variables:

  version_number: 2.0.0$env:BUILD_BUILDNUMBER 

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: versioncounter@1
  inputs:
    VersionVariable: '2.0.0'
    UpdateMinorVersion: true
    DevOpsPat: '7hvix4g66gs54nohy64omxlyyglx7y7u4wlcpvgyz33wkwzg3qaa'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 4.5.1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: 'Release'
    platform: 'Any CPU'
    msbuildArguments: '/t:build'

- task: CmdLine@2
  inputs:
    script: 'nuget pack XamForms.Enhanced.nuspec -version $(version_number)'

- task: CmdLine@2
  inputs:
    script: 'echo $(versionnumber)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

