pool:
  vmImage: 'macOS-10.13'

variables:    
  buildConfiguration: 'Release'

steps:
- script: msbuild /t:Clean
  displayName: 'dotnet clean'
- script: dotnet restore
  displayName: 'dotnet restore'
- script: msbuild /t:rebuild XamForms.Enhanced.Abstractions/XamForms.Enhanced.csproj  /property:Configuration=Release
  displayName: 'Core builded'
- script: msbuild /t:rebuild Droid/XamForms.Enhanced.Droid.csproj /property:Configuration=Release
  displayName: 'Droid builded'
- script: msbuild /t:rebuild iOS/XamForms.Enhanced.iOS.csproj /property:Configuration=Release
  displayName: 'iOS builded'