pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  displayName: 'Cake Build script'
  inputs:
    targetType: filePath
    filePath: ./build.sh
    arguments: '--target=$(target) --configuration=$(configuration) --verbosity=$(verbosity) --outputDir=$(Build.ArtifactStagingDirectory)'
    failOnStderr: true