pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  displayName: 'Cake Build script'
  inputs:
    targetType: filePath
    filePath: ./build.sh
    arguments: '--target=$(target) --configuration=$(configuration) --outputDir=$(Build.ArtifactStagingDirectory)'
    failOnStderr: true

- task: PublishBuildArtifacts@1
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/artifacts'
    Contents: '*.nupkg'
    TargetFolder: '$(build.ArtifactStagingDirectory)'