trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 4.5.1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: 'Release'
    platform: 'Any CPU'
    msbuildArguments: '/t:build'
    
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: '$(Release)'
    platform: 'Any CPU'
    msbuildArguments: '/t:pack /p:PackageVersion=$(Build.BuildNumber) /p:PackageOutputPath=$(build.artifactstagingdirectory)/public /p:AssemblyFileVersion=$(Build.BuildNumber)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'