pool:
  vmImage: 'macOS-10.13'

variables:    
  buildConfiguration: 'Release'

- task: XamariniOS@2
  inputs:
    solutionFile: '**/*.sln'
    configuration: 'Release'
    packageApp: false
    buildForSimulator: true
    runNugetRestore: true