
pool:
  vmImage: 'macOS-10.13'

variables:    
  buildConfiguration: 'Release'

steps:
- task: XamariniOS@2
  inputs:
    solutionFile: '**/*iOS.csproj'
    configuration: '$(buildConfiguration)'
    buildForSimulator: true